"""Fifth

Revision ID: 06d32eb4fda5
Revises: 30800f9cd59d
Create Date: 2022-09-16 22:08:40.048928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d32eb4fda5'
down_revision = '30800f9cd59d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
