"""Seventh

Revision ID: 0cd8524e44b9
Revises: 0d159ae57854
Create Date: 2022-09-16 23:00:35.338840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd8524e44b9'
down_revision = '0d159ae57854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
