"""Seventh

Revision ID: 0d159ae57854
Revises: 1c645a63a309
Create Date: 2022-09-16 22:54:08.873979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d159ae57854'
down_revision = '1c645a63a309'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
