"""Seventh

Revision ID: 1c645a63a309
Revises: 53b65c84cd42
Create Date: 2022-09-16 22:50:27.650106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c645a63a309'
down_revision = '53b65c84cd42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
