"""Fourth

Revision ID: 30800f9cd59d
Revises: f34575e198a0
Create Date: 2022-09-16 21:59:47.714720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30800f9cd59d'
down_revision = 'f34575e198a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
