"""Fourth

Revision ID: 37159b717836
Revises: 3d87506f0187
Create Date: 2022-09-16 21:25:39.921773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37159b717836'
down_revision = '3d87506f0187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cars_model', table_name='cars')
    op.drop_index('ix_cars_owner', table_name='cars')
    op.drop_index('ix_cars_vehicle_mileage', table_name='cars')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cars_vehicle_mileage', 'cars', ['vehicle_mileage'], unique=False)
    op.create_index('ix_cars_owner', 'cars', ['owner'], unique=False)
    op.create_index('ix_cars_model', 'cars', ['model'], unique=False)
    # ### end Alembic commands ###
