"""Fourth

Revision ID: 3d87506f0187
Revises: ba1703d85630
Create Date: 2022-09-16 21:18:09.903355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d87506f0187'
down_revision = 'ba1703d85630'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
