"""Seventh

Revision ID: 45b2f3c51a38
Revises: 802479ebaf0b
Create Date: 2022-09-16 23:24:53.283849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b2f3c51a38'
down_revision = '802479ebaf0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
