"""Sixth

Revision ID: 47b8e769aaa9
Revises: ab53ec218a97
Create Date: 2022-09-16 21:31:10.134095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b8e769aaa9'
down_revision = 'ab53ec218a97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
