"""Sixth

Revision ID: 53b65c84cd42
Revises: 9bed5a072736
Create Date: 2022-09-16 22:43:43.643490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b65c84cd42'
down_revision = '9bed5a072736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
