"""First

Revision ID: 78841b94178b
Revises: 47b8e769aaa9
Create Date: 2022-09-16 21:54:03.716269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78841b94178b'
down_revision = '47b8e769aaa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cars_license_plate', table_name='cars')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cars_license_plate', 'cars', ['license_plate'], unique=False)
    # ### end Alembic commands ###
