"""Seventh

Revision ID: 802479ebaf0b
Revises: 0cd8524e44b9
Create Date: 2022-09-16 23:09:34.011113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802479ebaf0b'
down_revision = '0cd8524e44b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
