"""Sixth

Revision ID: 9bed5a072736
Revises: fa7cc971fac0
Create Date: 2022-09-16 22:43:39.712267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bed5a072736'
down_revision = 'fa7cc971fac0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('license_plate', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('vehicle_mileage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('license_plate')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
