"""Fifth

Revision ID: ab53ec218a97
Revises: 37159b717836
Create Date: 2022-09-16 21:26:26.975583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab53ec218a97'
down_revision = '37159b717836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'vehicle_mileage',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'vehicle_mileage',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
