"""aboba

Revision ID: b1c2e3220152
Revises: dcbbc0f51da2
Create Date: 2022-09-17 21:03:33.933442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c2e3220152'
down_revision = 'dcbbc0f51da2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
