"""Second

Revision ID: ba1703d85630
Revises: e970c7ae1571
Create Date: 2022-09-16 21:10:24.737560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1703d85630'
down_revision = 'e970c7ae1571'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'license_plate',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index('ix_cars_id', table_name='cars')
    op.drop_column('cars', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_cars_id', 'cars', ['id'], unique=False)
    op.alter_column('cars', 'license_plate',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
