"""Seventh

Revision ID: d084a1d06b61
Revises: 45b2f3c51a38
Create Date: 2022-09-17 13:28:29.566396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd084a1d06b61'
down_revision = '45b2f3c51a38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
