"""aboba

Revision ID: d759ee5eff48
Revises: b1c2e3220152
Create Date: 2022-09-17 21:05:06.555733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd759ee5eff48'
down_revision = 'b1c2e3220152'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
