"""Second

Revision ID: e970c7ae1571
Revises: f4118d1e66b4
Create Date: 2022-09-16 21:07:01.504942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e970c7ae1571'
down_revision = 'f4118d1e66b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=250), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('vehicle_mileage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'vehicle_mileage')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_license_plate'), 'cars', ['license_plate'], unique=False)
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    op.create_index(op.f('ix_cars_owner'), 'cars', ['owner'], unique=False)
    op.create_index(op.f('ix_cars_vehicle_mileage'), 'cars', ['vehicle_mileage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_vehicle_mileage'), table_name='cars')
    op.drop_index(op.f('ix_cars_owner'), table_name='cars')
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_index(op.f('ix_cars_license_plate'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
