"""Third

Revision ID: f34575e198a0
Revises: bf8f3f280b51
Create Date: 2022-09-16 21:59:30.247647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34575e198a0'
down_revision = 'bf8f3f280b51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
