"""Sixth

Revision ID: fa7cc971fac0
Revises: 06d32eb4fda5
Create Date: 2022-09-16 22:17:19.473648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7cc971fac0'
down_revision = '06d32eb4fda5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
